server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:db-epicategory
    driverClassName: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus